# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
---
name: "Low dep tests: providers"
on:  # yamllint disable-line rule:truthy
  workflow_call:
permissions: {}
jobs:
  prov-lowestdeps-14-3-10-cncf-kubernetes:
    name: "prov:LowestDeps:14:3.10:cncf.kubernetes"
    runs-on: ["ubuntu-latest"]
    timeout-minutes: 90
    steps:
      - name: "DEMO - this job ran nothing, see DEMO_NOTICE.md"
        run: echo "DEMO - this job ran nothing, see DEMO_NOTICE.md"
      - name: "Run"
        run: sleep 487
  prov-lowestdeps-14-3-10-google:
    name: "prov:LowestDeps:14:3.10:google"
    runs-on: ["ubuntu-latest"]
    timeout-minutes: 90
    steps:
      - name: "DEMO - this job ran nothing, see DEMO_NOTICE.md"
        run: echo "DEMO - this job ran nothing, see DEMO_NOTICE.md"
      - name: "Run"
        run: sleep 903
  prov-lowestdeps-14-3-10-common-compat:
    name: "prov:LowestDeps:14:3.10:common.compat"
    runs-on: ["ubuntu-latest"]
    timeout-minutes: 90
    steps:
      - name: "DEMO - this job ran nothing, see DEMO_NOTICE.md"
        run: echo "DEMO - this job ran nothing, see DEMO_NOTICE.md"
      - name: "Run"
        run: sleep 451
  prov-lowestdeps-14-3-10-amazon-apache-flink:
    name: "prov:LowestDeps:14:3.10:amazon...apache.flink"
    runs-on: ["ubuntu-latest"]
    timeout-minutes: 90
    steps:
      - name: "DEMO - this job ran nothing, see DEMO_NOTICE.md"
        run: echo "DEMO - this job ran nothing, see DEMO_NOTICE.md"
      - name: "Run"
        run: sleep 997
  prov-lowestdeps-14-3-10-apache-spark-celery:
    name: "prov:LowestDeps:14:3.10:apache.spark...celery"
    runs-on: ["ubuntu-latest"]
    timeout-minutes: 90
    steps:
      - name: "DEMO - this job ran nothing, see DEMO_NOTICE.md"
        run: echo "DEMO - this job ran nothing, see DEMO_NOTICE.md"
      - name: "Run"
        run: sleep 422
